<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(RootNamespace).Tests</RootNamespace>
    <BaseOutputPath>obj\bin</BaseOutputPath>
    <IsPackable>false</IsPackable>

    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1707</NoWarn>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />

  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>